name: Build and Deploy Code

on: [push, pull_request]

env:
  DATABASE_HOSTNAME: localhost1

jobs: 
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: root123
      DATABASE_NAME: fastapi_test
      DATABASE_USERNAME: postgres
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: root123
          POSTGRES_DB: fastapi_test
          POSTGRES_PORT: 5432
          options: >-
            --health-cmd pg_isready
            --health-inteval 10s
            --health-retries 5
            --health-timeout 5s

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2 
      - name: Install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test env
        run: echo "$DATABASE_HOSTNAME"  
      - name: test with pytest
        run: |
          pip install pytest
          pytest -v -s

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: test env
        run: |
          echo " ${{ secrets.DATABASE_PORT }} "
          echo " ${{ secrets.DATABASE_HOSTNAME }} " 
          echo " ${{ secrets.DATABASE_PORT }} "
          echo " ${{ secrets.DATABASE_PASSWORD }} "
          echo " ${{ secrets.DATABASE_NAME }} "
          echo " ${{ secrets.DATABASE_USERNAME }} "
          echo " ${{ secrets.SECRET_KEY }} "
          echo " ${{ secrets.ALGORITHM }} "
          echo " ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }} "

  